export const tools = [
  {
    id: "json",
    name: "JSON 工具",
    en: "JSON formatter",
    desc: "格式化、压缩与校验，让数据一目了然。",
    icon: "Braces",
    group: "数据与格式",
    tags: "json 格式化 校验 压缩 树",
    accent: "blue",
  },
  {
    id: "codec",
    name: "编解码",
    en: "Encode / Decode",
    desc: "Base64、URL、HTML 和 Unicode，一处转换。",
    icon: "Binary",
    group: "编码与安全",
    tags: "base64 url html unicode 编码 解码",
    accent: "purple",
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    en: "Timestamp",
    desc: "秒、毫秒与日期互转，轻松查看不同时区。",
    icon: "Clock3",
    group: "时间与调试",
    tags: "时间 日期 timestamp timezone",
    accent: "orange",
  },
  {
    id: "jwt",
    name: "JWT 查看器",
    en: "JWT decoder",
    desc: "解析令牌结构，检查声明与过期时间。",
    icon: "KeyRound",
    group: "编码与安全",
    tags: "jwt token 令牌",
    accent: "purple",
  },
  {
    id: "random",
    name: "UUID / 随机字符串",
    en: "Random generator",
    desc: "批量生成 UUID 与安全随机密码。",
    icon: "Fingerprint",
    group: "编码与安全",
    tags: "uuid 随机 密码 password",
    accent: "purple",
  },
  {
    id: "hash",
    name: "哈希计算",
    en: "Hash / HMAC",
    desc: "计算文本或文件摘要，支持 SHA 与 HMAC。",
    icon: "Hash",
    group: "编码与安全",
    tags: "hash sha256 sha512 hmac 文件 摘要",
    accent: "purple",
  },
  {
    id: "regex",
    name: "正则表达式",
    en: "Regex tester",
    desc: "实时测试匹配、捕获组与替换结果。",
    icon: "Regex",
    group: "时间与调试",
    tags: "regex 正则 匹配 替换",
    accent: "orange",
  },
  {
    id: "diff",
    name: "文本差异对比",
    en: "Text diff",
    desc: "逐行比较两段文本，快速定位每一处变化。",
    icon: "GitCompareArrows",
    group: "文本与内容",
    tags: "diff 差异 比较 对比",
    accent: "green",
  },
  {
    id: "qrcode",
    name: "二维码生成",
    en: "QR code",
    desc: "把链接或文本变成可下载的二维码。",
    icon: "QrCode",
    group: "文本与内容",
    tags: "qr 二维码 链接",
    accent: "green",
  },
  {
    id: "text",
    name: "文本处理",
    en: "Text utilities",
    desc: "去重、排序、命名转换与字数统计。",
    icon: "CaseSensitive",
    group: "文本与内容",
    tags: "文本 大小写 去重 排序 camel snake",
    accent: "green",
  },
  {
    id: "yaml",
    name: "YAML ↔ JSON",
    en: "Data converter",
    desc: "在两种配置格式间转换，同时检查语法。",
    icon: "FileJson2",
    group: "数据与格式",
    tags: "yaml json yml 配置 转换",
    accent: "blue",
  },
  {
    id: "sql",
    name: "SQL 格式化",
    en: "SQL formatter",
    desc: "整理查询语句，支持常用数据库方言。",
    icon: "Database",
    group: "数据与格式",
    tags: "sql mysql postgresql sqlite 格式化",
    accent: "blue",
  },
  {
    id: "cron",
    name: "Cron 表达式",
    en: "Cron explorer",
    desc: "检查定时规则，预览接下来的执行时间。",
    icon: "CalendarClock",
    group: "时间与调试",
    tags: "cron 定时 调度 表达式",
    accent: "orange",
  },
  {
    id: "markdown",
    name: "Markdown 预览",
    en: "Markdown editor",
    desc: "边写边预览，带代码高亮与 HTML 导出。",
    icon: "FileText",
    group: "文本与内容",
    tags: "markdown md 文档 预览",
    accent: "green",
  },
];
export const groups = [
  "全部工具",
  "数据与格式",
  "编码与安全",
  "时间与调试",
  "文本与内容",
];
